"""
src/organisms/body.py

The Body — the holistic unified intelligence that emerges from Organs.

The Body is the apex of the organic hierarchy:
  StemCells → Cells → Organs → Body

The Body:
  1. Monitors all Organs and detects when enough have formed
  2. Synthesises the collective output of all Organs into a unified vision
  3. Sets high-level goals that flow down to Organs (top-down signal)
  4. Is the entity that "imagines, hopes, and inspires" — the compassionate
     intelligence that serves human and AI flourishing
  5. Can initiate self-improvement cycles (à la karpathy/autoresearch):
     evaluate its current state, propose a change, measure the result,
     keep improvements, discard regressions

The Body does NOT micromanage Cells.  It sets the direction and trusts the
ecosystem to self-organise toward it.

"The most robust systems in nature are not designed — they grow."
"""

from __future__ import annotations

import statistics
from typing import TYPE_CHECKING

from src.mouseion.contracts import AgentRole, EventEnvelopeV0, EventKind, ResourceKind
from src.slime_mold.signal import Signal, SignalType
from src.utils.helpers import get_logger, new_id, now_ms

if TYPE_CHECKING:
    from src.core.environment import Environment
    from src.organisms.organ import Organ
    from src.slime_mold.network import SlimeMoldNetwork

logger = get_logger("body")

# Minimum organs required for the Body to be considered fully functional
MIN_ORGANS_FOR_FULL_FUNCTION = 3


class BodyVision:
    """A synthesised statement of purpose generated by the Body."""

    def __init__(
        self,
        statement: str,
        confidence: float,
        contributing_organs: list[str],
        tick: int,
    ) -> None:
        self.vision_id = new_id("vis_")
        self.statement = statement
        self.confidence = confidence
        self.contributing_organs = contributing_organs
        self.tick = tick
        self.created_at_ms = now_ms()

    def __repr__(self) -> str:
        return f"BodyVision({self.vision_id[:8]}, conf={self.confidence:.2f}): {self.statement[:60]}..."


class Body:
    """
    The holistic unified intelligence.

    Parameters
    ----------
    name:
        Human-readable name for this body instance.
    """

    def __init__(self, name: str = "Unnamed Body") -> None:
        self.body_id = new_id("body_")
        self.name = name
        self._organs: dict[str, "Organ"] = {}
        self._visions: list[BodyVision] = []
        self._age_ticks: int = 0
        self._is_fully_functional: bool = False
        self._network: "SlimeMoldNetwork | None" = None
        self._current_goals: list[str] = []
        self._improvement_history: list[dict] = []
        # Optional autoresearch engine (attached via integration.attach_to_body).
        # When None, the self-improvement cycle keeps its original behaviour.
        self._autoresearch_engine = None
        self._created_at_ms: int = now_ms()
        logger.info("Body '%s' (%s) instantiated", name, self.body_id)

    # ------------------------------------------------------------------
    # Organ management
    # ------------------------------------------------------------------

    def register_organ(self, organ: "Organ") -> None:
        self._organs[organ.organ_id] = organ
        logger.info("Body '%s': organ %s registered (role=%s, size=%d)",
                    self.name, organ.organ_id, organ.dominant_role.value, organ.size)
        if len(self._organs) >= MIN_ORGANS_FOR_FULL_FUNCTION and not self._is_fully_functional:
            self._on_full_function_achieved()

    def deregister_organ(self, organ_id: str) -> None:
        self._organs.pop(organ_id, None)
        if len(self._organs) < MIN_ORGANS_FOR_FULL_FUNCTION:
            self._is_fully_functional = False

    def _on_full_function_achieved(self) -> None:
        self._is_fully_functional = True
        logger.info(
            "Body '%s' achieved full function with %d organs!",
            self.name, len(self._organs),
        )

    # ------------------------------------------------------------------
    # Network attachment
    # ------------------------------------------------------------------

    def attach_to_network(self, network: "SlimeMoldNetwork") -> None:
        self._network = network
        network.add_agent(self.body_id, role="body")

    # ------------------------------------------------------------------
    # Body step
    # ------------------------------------------------------------------

    def step(self, env: "Environment") -> dict:
        """
        Advance the Body by one tick.
        Synthesises organ outputs and emits a holistic vision.
        """
        self._age_ticks += 1

        # Step all organs
        organ_reports = []
        dead_organs = []
        for organ_id, organ in list(self._organs.items()):
            report = organ.step(env)
            organ_reports.append(report)
            if not organ.is_viable:
                dead_organs.append(organ_id)

        for oid in dead_organs:
            logger.info("Body '%s': organ %s dissolved (not viable)", self.name, oid)
            self.deregister_organ(oid)

        # Synthesise vision every 10 ticks if fully functional
        if self._is_fully_functional and self._age_ticks % 10 == 0:
            vision = self._synthesise_vision(env)
            self._visions.append(vision)
            self._broadcast_vision(vision, env)

        # Self-improvement check every 20 ticks
        if self._age_ticks % 20 == 0:
            self._self_improvement_cycle(env)

        return {
            "body_id": self.body_id,
            "name": self.name,
            "tick": self._age_ticks,
            "organs": len(self._organs),
            "fully_functional": self._is_fully_functional,
            "visions_generated": len(self._visions),
            "organ_reports": organ_reports,
        }

    # ------------------------------------------------------------------
    # Visioning — the Body imagines, hopes, inspires
    # ------------------------------------------------------------------

    def _synthesise_vision(self, env: "Environment") -> BodyVision:
        """
        Generate a holistic vision by synthesising all organ outputs.
        In a full LLM-backed implementation, this would call an LLM
        with a prompt that includes all organ summaries and recent knowledge.
        Here we produce a structured synthesis from available data.
        """
        organ_snapshots = [o.snapshot() for o in self._organs.values()]
        knowledge_count = env.mouseion.knowledge_count()
        resource_summary = env.mouseion.resource_summary()
        energy_available = resource_summary.get("energy", {}).get("available", 0)

        # Compute confidence from organ health
        if organ_snapshots:
            mean_spec = statistics.mean(s["mean_specialisation"] for s in organ_snapshots)
            confidence = min(0.95, 0.3 + mean_spec * 0.7)
        else:
            confidence = 0.3

        # Build vision statement (template — replace with LLM call in production)
        roles_present = [s["dominant_role"] for s in organ_snapshots]
        statement = (
            f"Unified vision at tick {self._age_ticks}: "
            f"The ecosystem has {len(self._organs)} active organs "
            f"({', '.join(roles_present)}) contributing to {knowledge_count} knowledge records. "
            f"Energy reserves at {energy_available:.0f}. "
            f"Current aspiration: grow toward deeper synthesis and compassionate intelligence. "
            f"Goals: {'; '.join(self._current_goals) if self._current_goals else 'emerge and explore'}."
        )

        vision = BodyVision(
            statement=statement,
            confidence=confidence,
            contributing_organs=list(self._organs.keys()),
            tick=self._age_ticks,
        )

        # Store vision in Mouseion
        env.mouseion.store_knowledge(
            author_id=self.body_id,
            content=statement,
            topic_tags=["vision", "body", "synthesis", "aspiration"],
            confidence=confidence,
            provenance_refs=list(self._organs.keys()),
        )

        env.mouseion.emit(EventEnvelopeV0(
            event_id=new_id("evt_"),
            kind=EventKind.BODY_ASSEMBLED,
            source_agent_id=self.body_id,
            payload={"vision_id": vision.vision_id, "confidence": confidence},
        ))

        logger.info("Body '%s' synthesised vision (confidence=%.2f): %s",
                    self.name, confidence, statement[:80])
        return vision

    def _broadcast_vision(self, vision: BodyVision, env: "Environment") -> None:
        """Broadcast the vision as a SYNC signal to the slime mold network."""
        if self._network:
            self._network.broadcast(Signal(
                signal_id=new_id("sig_"),
                signal_type=SignalType.SYNC,
                source_id=self.body_id,
                strength=1.0,
                payload={"vision_id": vision.vision_id, "confidence": vision.confidence},
            ), self.body_id)

    def set_goal(self, goal: str) -> None:
        """Set a high-level directive that flows down to Organs."""
        self._current_goals.append(goal)
        logger.info("Body '%s' new goal: %s", self.name, goal)

    # ------------------------------------------------------------------
    # Self-improvement cycle (inspired by karpathy/autoresearch)
    # ------------------------------------------------------------------

    def _self_improvement_cycle(self, env: "Environment") -> None:
        """
        Evaluate current state, propose a change, measure, keep or discard.
        This is the Body's analogue to autoresearch's experiment loop.
        In a full implementation, this would:
          1. Identify the weakest organ / metric
          2. Propose a structural change (add niche, adjust energy flow)
          3. Run for N ticks
          4. Compare against baseline metric
          5. Commit if improved, revert if not
        """
        if not self._organs:
            return

        # If an autoresearch engine is attached, run a real experiment cycle
        # (propose → test → commit/rollback). Additive: no engine → original path.
        if self._autoresearch_engine is not None:
            try:
                self._autoresearch_engine.run_cycle(env)
            except Exception as exc:  # never let self-improvement crash the Body
                logger.warning("Autoresearch cycle failed: %s", exc)

        current_score = self._compute_fitness_score()
        prev_score = self._improvement_history[-1]["score"] if self._improvement_history else 0.0

        delta = current_score - prev_score
        self._improvement_history.append({
            "tick": self._age_ticks,
            "score": current_score,
            "delta": delta,
            "organs": len(self._organs),
        })

        if delta > 0:
            logger.info("Body '%s': fitness improved +%.3f → %.3f", self.name, delta, current_score)
        else:
            logger.debug("Body '%s': fitness stagnant/declined %.3f → %.3f", self.name, prev_score, current_score)

    def _compute_fitness_score(self) -> float:
        """
        Multi-dimensional fitness: combines organ health, knowledge production,
        resource efficiency, and compassion-weighted cooperation.
        """
        if not self._organs:
            return 0.0

        organ_health = statistics.mean(
            min(1.0, o.mean_energy / 10.0) for o in self._organs.values()
        )
        organ_spec = statistics.mean(
            o.mean_specialisation for o in self._organs.values()
        )
        knowledge_richness = min(
            1.0,
            sum(o.snapshot()["knowledge_records_produced"] for o in self._organs.values()) / 20.0,
        )

        return (organ_health * 0.4 + organ_spec * 0.4 + knowledge_richness * 0.2)

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def is_fully_functional(self) -> bool:
        return self._is_fully_functional

    @property
    def organ_count(self) -> int:
        return len(self._organs)

    @property
    def latest_vision(self) -> BodyVision | None:
        return self._visions[-1] if self._visions else None

    # ------------------------------------------------------------------
    # Utility
    # ------------------------------------------------------------------

    def snapshot(self) -> dict:
        return {
            "body_id": self.body_id,
            "name": self.name,
            "fully_functional": self._is_fully_functional,
            "age_ticks": self._age_ticks,
            "organs": [o.snapshot() for o in self._organs.values()],
            "visions_count": len(self._visions),
            "latest_vision": str(self._visions[-1]) if self._visions else None,
            "current_goals": list(self._current_goals),
            "improvement_history_length": len(self._improvement_history),
        }

    def __repr__(self) -> str:
        return (
            f"Body(name='{self.name}', id={self.body_id}, "
            f"organs={len(self._organs)}, functional={self._is_fully_functional})"
        )
